SELECT YEAR(X.DIFFERENTIATION_DATE) AS YEAR, (Y.MC - X.SIZE_OF_COLONY) AS YEAR_DEV, X.ID
FROM ECOLI_DATA AS X,
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MC
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) AS Y
WHERE YEAR(X.DIFFERENTIATION_DATE) = Y.YEAR
ORDER BY YEAR, YEAR_DEV
