(SELECT DATE_FORMAT (SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE "2022-03%")

UNION 

(SELECT DATE_FORMAT (SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE "2022-03%")

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

-- DATE_FORMAT(column 명, "%Y-%m-%d") as column 명 : 년, 월, 일 로 date 형식 만들기 
-- like "% %" : 문자열 형식 비교 방법
-- NULL AS USER_ID : null 값으로 출력 만들기 