SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME = (
    SELECT MIN(DATETIME)
    FROM ANIMAL_INS
)

SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

-- 가장 크거나 작은 값 찾을때 ORDER BY 로 정렬 후에 
-- LIMIT 1 : 정렬된 가장 위에 있는 값 가져오기 