SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK, BOOK_SALES
WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
AND SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY ASC